### ISSUE TITLE
Implement 2-pass parsing to properly handle in-buffer settings that affect parsing of content

### ISSUE THREAD

**Issue by transitracer** [xiaoxinghu/orgajs#28]
`TODO` is the only current in-buffer setting affected by this, but another unimplemented example would be `PRIORITIES`.

This is inconsistent with actual org-mode behavior and can cause issues in parsing org files, correct behavior requires two passes, one to discover in-buffer settings and another to actually parse the file into an AST.

Example:  
```js
> const { parse } = require('orga')
[...]
> parse('* TADA Header\n#+TODO: TADA | DANE').children[0].children[0].keyword
undefined
> parse('#+TODO: TADA | DANE\n* TADA Header').children[0].children[0].keyword
'TADA'
```

**Comment by xiaoxinghu** [comment]
Do you have a use case for putting the TODO in buffer setting anywhere but the top of the file? Because I understand that it may work a little differently compare to org-mode, but it's very inefficient to do 2-pass parsing, especially for large files. There's gotta be good reasons for doing that. If 99.99% of people still put them at the beginning of their files anyway, and the 0.01% don't have a compelling reason to do otherwise, then I think we should stick with current implementation. 

Also I think it makes scene in a markup language (instead of a real programming language), the position of your markup implies it take effects after them.

**Comment by transitracer** [comment]
No, if it's not a goal to emulate actual org-mode functionality on the edge cases then there's no real reason I suppose
